"""Add tension to racquet model

Revision ID: 3516c829b345
Revises: 94b01aca0a1c
Create Date: 2023-10-10 17:26:26.487963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3516c829b345'
down_revision = '94b01aca0a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racquets', sa.Column('tension_high', sa.String(), nullable=True))
    op.add_column('racquets', sa.Column('tension_low', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('racquets', 'tension_low')
    op.drop_column('racquets', 'tension_high')
    # ### end Alembic commands ###
