"""empty message

Revision ID: 473e72b9a830
Revises: 86c61e6ada6c
Create Date: 2022-06-13 16:58:29.362538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473e72b9a830'
down_revision = '86c61e6ada6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('racquets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('headsize', sa.Integer(), nullable=True),
    sa.Column('num_crosses', sa.Integer(), nullable=True),
    sa.Column('num_mains', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('len_crosses', sa.String(), nullable=True),
    sa.Column('len_mains', sa.String(), nullable=True),
    sa.Column('start_cross', sa.String(), nullable=True),
    sa.Column('start_main', sa.String(), nullable=True),
    sa.Column('tie_cross', sa.String(), nullable=True),
    sa.Column('tie_main', sa.String(), nullable=True),
    sa.Column('skip_cross', sa.String(), nullable=True),
    sa.Column('skip_main', sa.String(), nullable=True),
    sa.Column('short_side', sa.String(), nullable=True),
    sa.Column('long_side', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('racquets')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
