"""Add pattern_type

Revision ID: 4ded6755b829
Revises: 473e72b9a830
Create Date: 2022-10-24 14:44:25.811448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ded6755b829'
down_revision = '473e72b9a830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'manufacturers', ['id'])
    op.create_unique_constraint(None, 'racquets', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'racquets', type_='unique')
    op.drop_constraint(None, 'manufacturers', type_='unique')
    op.drop_table('pattern_types')
    # ### end Alembic commands ###
