"""Add pattern_type to racquet

Revision ID: 94b01aca0a1c
Revises: 4ded6755b829
Create Date: 2022-10-27 14:43:24.097523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b01aca0a1c'
down_revision = '4ded6755b829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pattern_types', ['id'])
    op.add_column('racquets', sa.Column('pattern_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'racquets', 'pattern_types', ['pattern_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'racquets', type_='foreignkey')
    op.drop_column('racquets', 'pattern_type_id')
    op.drop_constraint(None, 'pattern_types', type_='unique')
    # ### end Alembic commands ###
