"""empty message

Revision ID: e118cf5215ad
Revises: 694693373907
Create Date: 2025-04-09 18:39:49.024284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e118cf5215ad'
down_revision = '694693373907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racquets', schema=None) as batch_op:
        batch_op.drop_constraint('racquets_pattern_type_id_fkey', type_='foreignkey')
        batch_op.drop_column('pattern_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racquets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pattern_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('racquets_pattern_type_id_fkey', 'pattern_types', ['pattern_type_id'], ['id'])

    # ### end Alembic commands ###
